version: 2

models:
  - name: mart_daily_stats
    columns:
      - name: day
        tests:
          - not_null
          - unique
      - name: events_count
        tests:
          - not_null

  - name: mart_region_stats
    columns:
      - name: region
        tests:
          - not_null

  - name: mart_significant_events
    columns:
      - name: event_id
        tests:
          - not_null
          - unique